### ISSUE TITLE
widgets/dtabbar.cpp:1516: infinite-recursion

### ISSUE THREAD

**Issue by dcb314** [linuxdeepin/dtkwidget#75]
widgets/dtabbar.cpp:1516:1: warning: all paths through this function will call itself [-Winfinite-recursion]

Source code is

int DTabBar::insertTab(int index, const QIcon &icon, const QString &text)
{
    return insertTab(index, icon, text);
}

**Comment by BLumia** [comment]
Sorry for the late reply. Since it's a pretty old issue, I'll close it for now.

We are using the [developer-center](https://github.com/linuxdeepin/developer-center/) repo to track issues and answer questions in discussion board, so if you still need help about building DTK, please feel free to ask us at [developer-center](https://github.com/linuxdeepin/developer-center/).

If you believe this issue still exists in the current release/codebase, please feel free to create a PR and we'll be happy to help you get it merged :)

Thanks!
